CREATE TABLE workshops (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name varchar(200)
);

CREATE TABLE participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  workshop_id bigint NOT NULL REFERENCES workshops(id) NOT NULL,
  user_id uuid NOT NULL REFERENCES users(id) DEFAULT uid() NOT NULL,
  name varchar(200)
);

INSERT INTO loving_families (name)
VALUES 
  ('Banana stand management'),
  ('Illusions'),
  ('real estate'),
;